version: 0.2

env:
  variables:
    IMAGE_TAG: "image-${CODEBUILD_RESOLVED_SOURCE_VERSION}"
    DOCKER_REGISTRY: "000000000000.dkr.ecr.us-west-2.amazonaws.com"

phases:
  build:
    commands:
      - echo "Building Docker image..."
      - echo "$DOCKER_REGISTRY/$IMAGE_TAG"
      - docker build -t "$DOCKER_REGISTRY/$IMAGE_TAG" .
      - echo "Pushing Docker image to the registry..."
      - $(aws ecr get-login --no-include-email --region us-west-2)
      - docker push "$DOCKER_REGISTRY/$IMAGE_TAG"

artifacts:
  type: "image"
  files:
    - "$DOCKER_REGISTRY/$IMAGE_TAG"
